# Generated by Django 3.2.13 on 2022-11-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='location',
            field=models.CharField(default=None, max_length=120),
            preserve_default=False,
        ),
    ]
