# Generated by Django 3.2.13 on 2022-11-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hits',
            field=models.PositiveBigIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
