# Generated by Django 3.2.13 on 2022-11-01 09:52

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='images/profile'),
        ),
    ]
